# Build the package and publish it to PyPI after tests pass.
name: Publish to PyPI
on:
  release:
    types: ["published"]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish:
    name: publish
    needs: [tests] # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}